### ISSUE TITLE
MacOS M1, Unsupported dtype Half

### ISSUE THREAD

**Issue by zakiso** [smthemex/ComfyUI_StoryDiffusion#106]
请问一下报错：
Storydiffusion_Sampler - Unsupported dtype Half 
有没有解决方法？感谢

设备： Macbook pro M1 Max 64GB

错误栈:
```
Prompt executed in 17.89 seconds
got prompt
start_merge_step:4
Sampler  [Taylor] 's cur_positive_prompts :[' a woman img, wearing a white T-shirt, blue loose hair.  wake up in the bed ; 8k,RAW', ' a woman img, wearing a white T-shirt, blue loose hair.  have breakfast by the window; 8k,RAW']
  0%|                                                            | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!! Unsupported dtype Half
Traceback (most recent call last):
  File "/Users/user/Documents/AI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/AI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/user/Documents/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/AI/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1689, in story_sampler
    for value in gen:
  File "/Users/user/Documents/AI/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 631, in process_generation
    id_images = pipe(
                ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1199, in __call__
    noise_pred = self.unet(
                 ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1281, in forward
    sample = upsample_block(
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 2511, in forward
    hidden_states, res_hidden_states = apply_freeu(
                                       ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/utils/torch_utils.py", line 142, in apply_freeu
    res_hidden_states = fourier_filter(res_hidden_states, threshold=1, scale=freeu_kwargs["s1"])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/utils/torch_utils.py", line 107, in fourier_filter
    x_freq = fftn(x, dim=(-2, -1))
             ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unsupported dtype Half
```

**Comment by smthemex** [comment]
看代码路径是kolor流程，我要梳理一下才行。

**Comment by zakiso** [comment]
感谢回复，另外请问您考虑工作机会吗？ 我们在招聘AI大模型工程师，非常适合您，如果您有兴趣可以联系我的邮箱可以吗？ zhiqiangdn@gmail.com

**Comment by zakiso** [comment]
兼职可以的，方便发一个联系方式到邮箱吗？ 感谢

**Comment by smthemex** [comment]
我邮箱联系你。。
