### ISSUE TITLE
**Node Type:** Storydiffusion_Sampler：list index out of range

### ISSUE THREAD

**Issue by lopezguan** [smthemex/ComfyUI_StoryDiffusion#108]
Seeking help, attempting to use dual roles, but failed. The required models have been downloaded to the corresponding folders.

![1729863321322](https://github.com/user-attachments/assets/f919380e-32c1-4fd2-a9ee-e9b9995277ff)

# ComfyUI Error Report
## Error Details
- **Node Type:** Storydiffusion_Sampler
- **Exception Type:** IndexError
- **Exception Message:** list index out of range
## Stack Trace
```
  File "E:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1628, in story_sampler
    positions_char_1 = [index for index, prompt in enumerate(prompts_origin) if char_origin[0] in prompt][

```
## System Information
- **ComfyUI Version:** v0.2.4-6-g5281090
- **Arguments:** E:\ComfyUI-aki-v1.4\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 4542804962
  - **Torch VRAM Total:** 6979321856
  - **Torch VRAM Free:** 6665186

## Logs
```
2024-10-25 20:19:27,403 - root - INFO - Total VRAM 12288 MB, total RAM 32676 MB
2024-10-25 20:19:27,403 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-25 20:19:29,144 - root - INFO - xformers version: 0.0.27
2024-10-25 20:19:29,144 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-25 20:19:29,144 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
2024-10-25 20:19:29,424 - root - INFO - Using xformers cross attention
2024-10-25 20:19:30,424 - root - INFO - [Prompt Server] web root: E:\ComfyUI-aki-v1.4\web
2024-10-25 20:19:35,057 - numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-10-25 20:19:35,057 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-10-25 20:19:35,577 - root - INFO - Total VRAM 12288 MB, total RAM 32676 MB
2024-10-25 20:19:35,577 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-25 20:19:35,577 - root - INFO - xformers version: 0.0.27
2024-10-25 20:19:35,577 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-25 20:19:35,577 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
2024-10-25 20:19:36,628 - root - WARNING - Traceback (most recent call last):

**Comment by lopezguan** [comment]
![image](https://github.com/user-attachments/assets/a99bd1fc-7d05-4bb5-8489-9282303e5846)
单个也不行哦

**Comment by smthemex** [comment]
一个角色，你前面的角色设定那里就要改成一个啊，你的前面那里有2个角色

**Comment by lopezguan** [comment]
> 一个角色，你前面的角色设定那里要改成一个啊，你前面那里有2个角色

就是场景描述区，有多少个角色，前面角色配置多少个角色是吗？目前最多两个角色对吧。
双角色出现同一张图像，
第一种情况文生图需要：
[角色1]   ;
[角色1]   ;
[角色2]   ;
[角色2]   ;
(角色1 and 角色2) ;
第二种情况直接是
图像参考[角色1]_img
[角色2]_img

场景描述区：
[角色1]_img+动作/背景；
[角色2]_img+动作/背景；
(角色1 and 角色2) +动作/背景；

是这么是使用吗？

**Comment by smthemex** [comment]
文生图因为需要有1句来预生产角色图片，所以要1个角色起码要2句，排列方式，[A]一行,[B]一行，后面谁在前后无所谓，然后第三行也可以是[A] and [B] (双角色标准)
图生图 1个角色起码有1句就可以

**Comment by lopezguan** [comment]
> 文生图因为需要有1句来预生产角色图片，所以要1个角色起码要2句，排列方式，[A]一行,[B]一行，后面谁在前后无所谓，然后第三行也可以是[A] and [B] (双角色标准) 图生图 1个角色起码有1句就可以

谢谢你的解答
