### ISSUE TITLE
can not import story diffusion custom node,please help me,thank you

### ISSUE THREAD

**Issue by sorrylala** [smthemex/ComfyUI_StoryDiffusion#122]
error like this : 
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/comfyui/nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/comfyui/custom_nodes/ComfyUI_StoryDiffusion/__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/comfyui/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 10, in <module>
    from diffusers import StableDiffusionXLPipeline, DiffusionPipeline,EulerDiscreteScheduler, UNet2DConditionModel,UniPCMultistepScheduler, AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/mnt/auto/comfyui/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 844, in __getattr__
    value = getattr(module, name)
  File "/mnt/auto/comfyui/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 844, in __getattr__
    value = getattr(module, name)
  File "/mnt/auto/comfyui/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/mnt/auto/comfyui/venv/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.lora_pipeline because of the following error (look up to see its traceback):
cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (/mnt/auto/comfyui/venv/lib/python3.10/site-packages/huggingface_hub/errors.py)

[2024-12-15 09:00] Cannot import /comfyui/custom_nodes/ComfyUI_StoryDiffusion module for custom nodes: Failed to import diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.lora_pipeline because of the following error (look up to see its traceback):
cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (/mnt/auto/comfyui/venv/lib/python3.10/site-packages/huggingface_hub/errors.py)

**Comment by sorrylala** [comment]
I download the last version of huggingface_hub,but tell me a new error:
[2024-12-15 11:32] Traceback (most recent call last):
  File "/comfyui/nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/comfyui/custom_nodes/ComfyUI_StoryDiffusion/__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/comfyui/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 20, in <module>
    from .model_loader_utils import  (story_maker_loader,kolor_loader,phi2narry,
  File "/comfyui/custom_nodes/ComfyUI_StoryDiffusion/model_loader_utils.py", line 12, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

**Comment by smthemex** [comment]
pip install omegaconf
