### ISSUE TITLE
I run the example workflow1006.json,but there is a error on sampler node

### ISSUE THREAD

**Issue by sorrylala** [smthemex/ComfyUI_StoryDiffusion#123]
I run the example workflow1006.json,but there is a error on sampler node, what's wrong with it : 

[2024-12-16 08:34] !!! Exception during processing!!! exceptions must derive from BaseException
[2024-12-16 08:34] Traceback (most recent call last):
  File "/comfyui/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/comfyui/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/comfyui/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/comfyui/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1819, in story_sampler
    raise "if using story-maker controlnet,The number of input control-images and scene prompts should be consistent!! "
TypeError: exceptions must derive from BaseException

![ADB9AEC7-4286-4059-8058-019F82C82B19](https://github.com/user-attachments/assets/26647395-2d58-47ec-8d68-1c47b5b2ed6e)

![3510782F-5581-452C-B90D-8D1E65851D7A](https://github.com/user-attachments/assets/c677a083-0cd9-433a-9074-1cf24cce79ac)

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/f046b3f3-15d9-4bdb-b4ae-7c3f8ea56792)
control img number = scene prompt lines number

**Comment by sorrylala** [comment]
I made control img number = scene prompt lines number, but it generate two empty image
![08CB93D2-2C0A-43FF-8114-2A85F128C522](https://github.com/user-attachments/assets/928a2ead-70a1-4edc-8d24-1ced7528906c)

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/a453894b-64b9-4862-acd1-41d90b505908)
your canny img is invalid, don't have such a big avatar

**Comment by sorrylala** [comment]
which kind imag I shoud use,can you give me a example?
