### ISSUE TITLE
CFGenerator' object has no attribute 'enable_vae_slicing | HELP

### ISSUE THREAD

**Issue by adbrasi** [smthemex/ComfyUI_StoryDiffusion#126]
this only happens when you type 'consi' in easyfunction. I tested it in different environments.

`2024-12-24T10:02:32.462496 - !!! Exception during processing !!! 'CFGenerator' object has no attribute 'enable_vae_slicing'
2024-12-24T10:02:32.463152 - Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 353, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1938, in story_sampler
    pipe.enable_vae_slicing()
AttributeError: 'CFGenerator' object has no attribute 'enable_vae_slicing'`

**Comment by smthemex** [comment]
Yes, this error is a logical error. When using ComfyUI classic mode, 'consi' mode should be invalidated. I fix it.

**Comment by adbrasi** [comment]
`2024-12-25T21:56:09.807162 - Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 353, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1408, in story_model_loader
    raise "Use comfyUI calss processing don't support consistory mode,please checke readme how to use consistory mode."
TypeError: exceptions must derive from BaseException`

i couldn't find anything in the readme explaining how to use consistory mode other than typing 'consi' in easy function. is there anything else? sorry for the inconvenience

**Comment by smthemex** [comment]
do not link any  other comfyUI node,just like this:
![image](https://github.com/user-attachments/assets/46f45dea-f68a-49c5-9d3a-a21068f59a50)
