### ISSUE TITLE
SyntaxError: invalid character '：' (U+FF1A)

### ISSUE THREAD

**Issue by Terminator-AGI** [smthemex/ComfyUI_StoryDiffusion#127]
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 2089, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1407
    if consistory：
                 ^
SyntaxError: invalid character '：' (U+FF1A)

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion module for custom nodes: invalid character '：' (U+FF1A) (Storydiffusion_node.py, line 1407)

**Comment by smthemex** [comment]
yeah i fix it in phone  so get this erro.
