### ISSUE TITLE
在“laion/CLIP-ViT-bigG-14-laion2B-39B-b160k” 一栏里填写你的本地clip模型的绝对路径，使用“/”

### ISSUE THREAD

**Issue by dy-gdut** [smthemex/ComfyUI_StoryDiffusion#19]
在“laion/CLIP-ViT-bigG-14-laion2B-39B-b160k” 一栏里填写你的本地clip模型的绝对路径，使用“/”   这句话怎么理解？

**Comment by smthemex** [comment]
如果你使用提前下载好的模型（直接下载那种，而不是hub自动下载的），你的模型文件会存在电脑的某个文件夹里，这里是提示你要填写F:/xxx/xxx/你的文件夹，不能填写windows的F:\xxx\xxx\你的文件夹   这种格式。

**Comment by dy-gdut** [comment]
Use_Single_XL_Model:
  path: "https://huggingface.co/RunDiffusion/Juggernaut-XL-v9/blob/main/Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors"
  single_files: true   ### if true, is a civitai model
  use_safetensors: true

RealVision:
  path: "SG161222/RealVisXL_V4.0"
  single_files: false
  use_safetensors: true

SDXL:
  path: "stabilityai/stable-diffusion-xl-base-1.0"
  single_files: false
  use_safetensors: true

Unstable:
  path: "stablediffusionapi/sdxl-unstable-diffusers-y"
  single_files: false
  use_safetensors: false

SDXL_Flash:
  path: "sd-community/sdxl-flash"
  single_files: false
  use_safetensors: true

Playground_v2p5:
  path: "playgroundai/playground-v2.5-1024px-aesthetic"
  single_files: false
  use_safetensors: true

这个配置文件里面没有看到这个clip的关键字

**Comment by smthemex** [comment]
这个是独立的，只是在使用双角色才会使用，如果不使用，是可以不填的。填写方式就是在节点栏aion/CLIP-ViT-bigG-14-laion2B-39B-b160k里填写，不需要去yaml文件

**Comment by dy-gdut** [comment]
有个问题想请教一下 模型读取还是读取不起来  能否微信截图指导一下   15377318053

**Comment by dy-gdut** [comment]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1069, in story_model_loader
    pipe = StableDiffusionXLPipeline.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\diffusers\loaders\single_file.py", line 491, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\diffusers\loaders\single_file.py", line 127, in load_single_file_sub_model
    loaded_sub_model = _legacy_load_scheduler(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 1472, in _legacy_load_scheduler
    return cls.from_config(scheduler_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\diffusers\configuration_utils.py", line 260, in from_config
    model = cls(**init_dict)
            ^^^^^^^^^^^^^^^^
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\diffusers\configuration_utils.py", line 658, in inner_init
    init(self, *args, **init_kwargs)
  File "C:\sd\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\venv\Lib\site-packages\diffusers\schedulers\scheduling_ddim.py", line 209, in __init__
    self.betas = torch.linspace(beta_start**0.5, beta_end**0.5, num_train_timesteps, dtype=torch.float32) ** 2
                                ~~~~~~~~~~^^~~~
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'float'

**Comment by smthemex** [comment]
第一次使用单体模型，需要能外网下载config文件，而且最好不要用魔改的单体模型，用一个大众点的。你这个没法联网的报错

**Comment by dy-gdut** [comment]
关键是我开了梯子  可以从抱脸去下载模型 用的模型是Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors

**Comment by dy-gdut** [comment]
有单体模型推荐吗 我试了很多个 都不行

**Comment by smthemex** [comment]
报错文件显示你是diffuser版本高于0.28，但是奇怪config文件读取失败。你试过选择非单体模型，会不会自动下载？如果不会，那是你没有开秋叶的镜像下载

**Comment by dy-gdut** [comment]
是不是开启了代理去下模型就可以了

**Comment by dy-gdut** [comment]
Error occurred when executing Storydiffusion_Model_Loader:

The provided pretrained_model_name_or_path "C:/sd/ComfyUI-aki-v1.3/ComfyUI-aki-v1.3/models/checkpoints/HoloAnime-XL——动漫风格SDXL模型_v2.7.safetensors" is neither a valid local path nor a valid repo id. Please check the parameter.

**Comment by dy-gdut** [comment]
错误变成这样子了

**Comment by smthemex** [comment]
单体模型首次运行是要开代理下config文件的，就是几M的文件，按理下载好了 以后就不用了。你去找我B站的微信群号吧，这里聊不是办法

**Comment by dy-gdut** [comment]
'Please add the triger word " img " behind the class word you want to customize, such as: man img or woman img' 现在是这个报错

**Comment by smthemex** [comment]
如果用图生图，必须有一个关键词 “img ”在角色的prompt里，你应该是不小心删掉了

**Comment by dy-gdut** [comment]
我采用的是text2ing那个节点

**Comment by smthemex** [comment]
是这样的，text2ing要生效，必须选择origin那个菜单的origin，迟点我改一下逻辑吧，有点啰嗦了。
