### ISSUE TITLE
ModuleNotFoundError: No module named 'ComfyUI_StoryDiffusion.ip_adapter'

### ISSUE THREAD

**Issue by laidingq** [smthemex/ComfyUI_StoryDiffusion#2]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 12, in <module>
    from .ip_adapter.attention_processor import IPAttnProcessor2_0
ModuleNotFoundError: No module named 'ComfyUI_StoryDiffusion.ip_adapter'

**Comment by smthemex** [comment]
pip install -r requirements.txt --target="your path\python_embeded\Lib\site-packages"

**Comment by laidingq** [comment]
安装好了 谢谢

**Comment by laidingq** [comment]
Successfully installed, thank you
