### ISSUE TITLE
 No module named 'diffusers'

### ISSUE THREAD

**Issue by Benbiubiu** [smthemex/ComfyUI_StoryDiffusion#30]
Traceback (most recent call last):
  File "C:\Users\80690\Desktop\ComfyUI - AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1907, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\80690\Desktop\ComfyUI - AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\80690\Desktop\ComfyUI - AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 14, in <module>
    from diffusers.image_processor import IPAdapterMaskProcessor
ModuleNotFoundError: No module named 'diffusers'

Cannot import C:\Users\80690\Desktop\ComfyUI - AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion module for custom nodes: No module named 'diffusers'
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

**Comment by smthemex** [comment]
diffusers must 0.28.0 or up ,因为内置MS-diffusion的原因，现在diffuser的版本需要高于0.28.0以上，你用的是整合包，可以在ComfyUI_windows\update 运行 update_comfyui_and_python_dependencies.bat 升级diffusers库，或者简单运行pip install -U diffusers 更新diffusers

**Comment by Benbiubiu** [comment]
大神 还是不行，update_comfyui_and_python_dependencies.bat 升级diffusers库
提示：Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\80690\AppData\Local\Temp\pip-install-xeo1naqt\xformers_a1a24dee3c1d4d69a18fbf6abe35715a\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\80690\AppData\Local\Temp\pip-install-xeo1naqt\xformers_a1a24dee3c1d4d69a18fbf6abe35715a\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by smthemex** [comment]
你去python_embeded 目录下，打开CMD ，粘贴 python pip install -u diffusers --target="C:/Users/80690/Desktop/ComfyUI - AI/ComfyUI_windows_portable/python_embeded/Lib/site-packages"  后面的这个路径你看一下对不对。我是按你的报错信息写的。

**Comment by Benbiubiu** [comment]
你写得是对的但是提示：[Errno 2] No such file or directory

**Comment by Benbiubiu** [comment]
<img width="864" alt="屏幕截图 2024-07-09 094958" src="https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/105950611/ad8f4803-57b2-4cc2-a14e-0491984ecc9c">

**Comment by smthemex** [comment]
ComfyUI - AI/ 这个路径应该错误了，不可能有换行符或者空格的，你找到site-packages 这个文件夹，然后复制浏览器的地址栏的地址，把所有的\都改成/ ,注意替换掉我后面写的那些，注意要有英文的引号"  " 。

**Comment by Benbiubiu** [comment]
去掉最前面的 python
提示：
<img width="859" alt="屏幕截图 2024-07-09 094958" src="https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/105950611/ab9acf1a-6c0d-4962-87a9-f1bcda44ecd1">

**Comment by Benbiubiu** [comment]
去掉最前面的python是有反应的，提示：
<img width="859" alt="屏幕截图 2024-07-09 094958" src="https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/105950611/a9a52b98-9974-4399-a1b1-9e1497469bfd">

**Comment by Benbiubiu** [comment]
\都改成/也是一样的提示

**Comment by Benbiubiu** [comment]
<img width="860" alt="屏幕截图 2024-07-09 094958" src="https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/105950611/c21802a2-7b02-4691-88cc-5f54a40b6b7b">
这样子可以吗？大神

**Comment by Benbiubiu** [comment]
还有救吗？o(╥﹏╥)o

**Comment by smthemex** [comment]
额，你把-u 改成-U 大写的。

**Comment by Benbiubiu** [comment]
果然成功安装了，但是好像还是不行

**Comment by smthemex** [comment]
要看报错信息才行。

**Comment by Benbiubiu** [comment]
下午好 大神 还是一样的报错信息
Traceback (most recent call last):
  File "C:\Users\80690\Desktop\ComfyUI-AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1907, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\80690\Desktop\ComfyUI-AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\80690\Desktop\ComfyUI-AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 14, in <module>
    from diffusers.image_processor import IPAdapterMaskProcessor
ModuleNotFoundError: No module named 'diffusers'

Cannot import C:\Users\80690\Desktop\ComfyUI-AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion module for custom nodes: No module named 'diffusers'
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

**Comment by Benbiubiu** [comment]
可能还是没有安装成功

**Comment by Benbiubiu** [comment]
路径明明是对的，还是提示没有文件或地址

**Comment by smthemex** [comment]
我看了一下，是无用代码忘记删掉了，不是你的问题
