### ISSUE TITLE
请问文生图是否支持双角色？

### ISSUE THREAD

**Issue by aadian** [smthemex/ComfyUI_StoryDiffusion#37]
提供的例子中貌似没有看到txt2img双角色的例子

**Comment by smthemex** [comment]
支持的，跟图生图一样，确保是(x and b )但是需要开启最下面的restart 才能启用一次加载模型，多次生成。

**Comment by aadian** [comment]
文生图的control_image是否是必须的，刚才加入这个节点可以成功输出双角色，赞。

如果去掉control_image这个节点，后台会报如下的错误：
!!! Exception during processing!!! 'control_image'
Traceback (most recent call last):
  File "/Users/kevin/dev/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/kevin/dev/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/kevin/dev/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/kevin/dev/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1421, in story_sampler
    control_image = kwargs["control_image"]
KeyError: 'control_image'

**Comment by smthemex** [comment]
不是必须的，如果不使用controlnet，一定要把controlnet设置为none，否则会需求control_image 的输入，然后报错

**Comment by aadian** [comment]
是的，谢谢大佬，搞定了
