### ISSUE TITLE
模型路径设置

### ISSUE THREAD

**Issue by Benbiubiu** [smthemex/ComfyUI_StoryDiffusion#43]
大佬 模型路径如何设置，您的模型设置教材我看不懂

**Comment by Benbiubiu** [comment]
<img width="924" alt="image" src="https://github.com/user-attachments/assets/99b139df-db70-4296-91f3-966f97875f2e">

**Comment by smthemex** [comment]
你的model路径下没有diffuser,不过我马上就要更新这个插件,就在今天稍等

**Comment by Benbiubiu** [comment]
好的 大佬谢谢您

**Comment by aadian** [comment]
拉了最新的代码，如果选择不输入repoid会出错，大佬帮忙看下

Some weights of the model checkpoint were not used when initializing CLIPTextModel:
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 17.16it/s]
!!! Exception during processing!!! 'module name can\'t be empty string ""'
Traceback (most recent call last):
  File "/Users/kevin/dev/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/kevin/dev/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/kevin/dev/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/kevin/dev/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1222, in story_model_loader
    pipe = load_models(ckpt_path, model_type=model_type,single_files=True,use_safetensors=True, device=device, photomaker_path=photomaker_path, lora=lora,
  File "/Users/kevin/dev/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/utils/load_models_utils.py", line 66, in load_models
    pipe.load_lora_weights(lora_path, adapter_name=trigger_words)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/diffusers/loaders/lora.py", line 1234, in load_lora_weights
    self.load_lora_into_unet(
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/diffusers/loaders/lora.py", line 401, in load_lora_into_unet
    unet.load_attn_procs(
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/diffusers/loaders/unet.py", line 217, in load_attn_procs
    is_model_cpu_offload, is_sequential_cpu_offload = self._process_lora(
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/diffusers/loaders/unet.py", line 350, in _process_lora
    inject_adapter_in_model(lora_config, self, adapter_name=adapter_name)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/mapping.py", line 179, in inject_adapter_in_model
    peft_model = tuner_cls(model, peft_config, adapter_name=adapter_name)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 139, in __init__
    super().__init__(model, config, adapter_name)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 166, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 372, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 223, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 314, in _create_new_module
    new_module = dispatcher(target, adapter_name, lora_config=lora_config, **kwargs)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 1107, in dispatch_default
    new_module = Conv2d(target, adapter_name, **kwargs)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 825, in __init__
    self.update_layer(
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 846, in update_layer
    self.lora_dropout[adapter_name] = lora_dropout_layer
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/torch/nn/modules/container.py", line 464, in __setitem__
    self.add_module(key, module)
  File "/opt/homebrew/anaconda3/envs/sdwebui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 592, in add_module
    raise KeyError("module name can't be empty string \"\"")
KeyError: 'module name can\'t be empty string ""'


![Uploading WechatIMG717.jpg…]()

**Comment by smthemex** [comment]
这个可能是你的底模有问题，你换个社区模型试试

**Comment by aadian** [comment]
> 这个可能是你的底模有问题，你换个社区模型试试

的确是，换其他的模型可以，谢大佬
