### ISSUE TITLE
一直提示Storydiffusion_Model_Loader exceptions must derive from BaseException，不知道该如何处理

### ISSUE THREAD

**Issue by aiwork11** [smthemex/ComfyUI_StoryDiffusion#66]
Detected legacy `from_single_file` loading behavior. Attempting to create the pipeline based on inferred components.
This may lead to errors if the model components are not correctly inferred.
To avoid this warning, please explicity pass the `config` argument to `from_single_file` with a path to a local diffusers model repo
e.g. `from_single_file(<my model checkpoint path>, config=<path to local diffusers model repo>)
or run `from_single_file` with `local_files_only=False` first to update the local cache directory with the necessary config files.

Loading pipeline components...:   0%|                                                            | 0/7 [00:00<?, ?it/s]
Detected legacy `from_single_file` loading behavior. Attempting to create the pipeline based on inferred components.
This may lead to errors if the model components are not correctly inferred.
To avoid this warning, please explicity pass the `config` argument to `from_single_file` with a path to a local diffusers model repo
e.g. `from_single_file(<my model checkpoint path>, config=<path to local diffusers model repo>)
or run `from_single_file` with `local_files_only=False` first to update the local cache directory with the necessary config files.

Loading pipeline components...:   0%|                                                            | 0/7 [00:00<?, ?it/s]
!!! Exception during processing !!! exceptions must derive from BaseException
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 101, in load_models
    pipe = PhotoMakerStableDiffusionXLPipelineV2.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 495, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 139, in load_single_file_sub_model
    loaded_sub_model = _legacy_load_scheduler(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 1548, in _legacy_load_scheduler
    return cls.from_config(scheduler_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 260, in from_config
    model = cls(**init_dict)
            ^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 653, in inner_init
    init(self, *args, **init_kwargs)
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_ddim.py", line 209, in __init__
    self.betas = torch.linspace(beta_start**0.5, beta_end**0.5, num_train_timesteps, dtype=torch.float32) ** 2
                                ~~~~~~~~~~^^~~~
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 106, in load_models
    pipe = PhotoMakerStableDiffusionXLPipelineV2.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 495, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 139, in load_single_file_sub_model
    loaded_sub_model = _legacy_load_scheduler(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 1548, in _legacy_load_scheduler
    return cls.from_config(scheduler_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 260, in from_config
    model = cls(**init_dict)
            ^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 653, in inner_init
    init(self, *args, **init_kwargs)
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_ddim.py", line 209, in __init__
    self.betas = torch.linspace(beta_start**0.5, beta_end**0.5, num_train_timesteps, dtype=torch.float32) ** 2
                                ~~~~~~~~~~^^~~~
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1502, in story_model_loader
    pipe = load_models(ckpt_path, model_type=model_type,single_files=True,use_safetensors=True, photomake_mode=photomake_mode,photomaker_path=photomaker_path, lora=lora,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 111, in load_models
    raise "load pipe error"
TypeError: exceptions must derive from BaseException

Prompt executed in 42.33 seconds

**Comment by smthemex** [comment]
因为runway跑路，而diffuser如果运行加载单体SDXL，默认要拉取runway的config，所以造成加载失败，我在更新里放了如何解决这个问题，代码层面的还没有修改。
简单来说，要么把diffusers更新到最新，要么去修改你的difffusers的文件，把runway的默认地址改过来。

**Comment by aiwork11** [comment]
代码修改了，storydiffusion插件重新下载，但是不知道为什么还是同样的提示
![微信截图_20240906154940](https://github.com/user-attachments/assets/4db2acd6-bcd4-40e4-88cc-731652204534)
![微信图片_20240906155054](https://github.com/user-attachments/assets/40597a38-0b5a-44cd-b6fa-5cf91278a74f)

**Comment by smthemex** [comment]
你再更新一下，我这里测试时能跑通的，可能要连一次外网

**Comment by smthemex** [comment]
跟地址没什么关系，之前无法登陆是runway的问题，我刚刚上传了本地路径的config，避免首次运行加载外网。你这个是最新的还是之前的运行结果。这些是警告，如果能跑通就没什么问题

**Comment by aiwork11** [comment]
我之前那张照片的运行结果是最新的，我是今天下午刚安装的diffusers，版本是0.30.2，刚重新下载storydiffusion插件，选择V1运行可以出图了，但是选择V2,并且填了auraface，但是到了sampler那里就运行不了
![微信截图_20240906185208](https://github.com/user-attachments/assets/692d71d2-4b6f-4b6c-a45d-eb51cdb09b08)
![微信图片_20240906184721](https://github.com/user-attachments/assets/cfbb9e8b-e0f6-43a9-9904-851fd8beccd5)

**Comment by smthemex** [comment]
auraface 要连抱脸下载模型，包括要有ox才行，我看你的保持是网络的问题。

**Comment by smthemex** [comment]
我在说明里说了，nf4目前只能用链接指定的那个模型，nf4模型只是我改了名字而已，当前的nf4模式，暂时无法跑其他模型，包括张吕敏的那个，你圈的右边那个是张吕敏的

**Comment by aiwork11** [comment]
明白了，谢谢回复，我还下载了seaartlab的comfyui_storydiffusion，对比下来它能用的模型要多些，但是用openart中的工作流很容易脸崩了，而且seaart只能最多出4张图，工作流是出3张，我自己增加过，最多出4张，并且大小貌似限制到512，就不能设置更大了。对比下来，我更愿意用您的这个版本的，虽然解决baseexpection问题花了一天时间，最后抱着试一试的心态发出提问，没想到您回复得很快，十分感谢。
