### ISSUE TITLE
Storydiffusion_Model_Loader

### ISSUE THREAD

**Issue by sunyiwk** [smthemex/ComfyUI_StoryDiffusion#73]
# ComfyUI Error Report
## Error Details
- **Node Type:** Storydiffusion_Model_Loader
- **Exception Type:** ValueError
- **Exception Message:** Pipeline <class 'ComfyUI_StoryDiffusion.utils.pipeline.PhotoMakerStableDiffusionXLPipeline'> expected {'unet', 'feature_extractor', 'vae', 'tokenizer_2', 'text_encoder_2', 'image_encoder', 'scheduler', 'text_encoder', 'tokenizer'}, but only {'vae', 'tokenizer_2', 'text_encoder_2', 'scheduler', 'text_encoder', 'tokenizer'} were passed.
## Stack Trace
```
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1850, in story_model_loader
    pipe = load_models(repo_id, model_type=model_type, single_files=False, use_safetensors=True,photomake_mode=photomake_mode,

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 89, in load_models
    pipe = PhotoMakerStableDiffusionXLPipeline.from_pretrained(

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)

  File "M:\new222_ComfyUI\ComfyUI_windows_portable\.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 961, in from_pretrained
    raise ValueError(

```
## System Information
- **ComfyUI Version:** v0.2.0-2-g00a5d08
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11793334272
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-18 23:19:24,666 - root - INFO - Total VRAM 12288 MB, total RAM 32677 MB
2024-09-18 23:19:24,666 - root - INFO - pytorch version: 2.4.0+cu124
2024-09-18 23:19:26,666 - root - INFO - xformers version: 0.0.27.post2
2024-09-18 23:19:26,666 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-18 23:19:26,666 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-09-18 23:19:27,143 - root - INFO - Using xformers cross attention
2024-09-18 23:19:28,439 - root - INFO - [Prompt Server] web root: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\web
2024-09-18 23:19:28,441 - root - INFO - Adding extra search path checkpoints M:\STABLE20\models/Stable-diffusion
2024-09-18 23:19:28,442 - root - INFO - Adding extra search path configs M:\STABLE20\models/Stable-diffusion
2024-09-18 23:19:28,442 - root - INFO - Adding extra search path vae M:\STABLE20\models/VAE
2024-09-18 23:19:28,442 - root - INFO - Adding extra search path loras M:\STABLE20\models/Lora
2024-09-18 23:19:28,442 - root - INFO - Adding extra search path loras M:\STABLE20\models/LyCORIS
2024-09-18 23:19:28,442 - root - INFO - Adding extra search path upscale_models M:\STABLE20\models/ESRGAN
2024-09-18 23:19:28,442 - root - INFO - Adding extra search path upscale_models M:\STABLE20\models/RealESRGAN
2024-09-18 23:19:28,443 - root - INFO - Adding extra search path upscale_models M:\STABLE20\models/SwinIR
2024-09-18 23:19:28,443 - root - INFO - Adding extra search path embeddings M:\STABLE20\embeddings
2024-09-18 23:19:28,443 - root - INFO - Adding extra search path hypernetworks M:\STABLE20\models/hypernetworks
2024-09-18 23:19:28,444 - root - INFO - Adding extra search path controlnet M:\STABLE20\extensions/sd-webui-controlnet/models
2024-09-18 23:19:31,558 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir IPAdapterModelLoader' might differ from the native display name.
2024-09-18 23:19:31,558 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir IPAdapterAdvanced' might differ from the native display name.
2024-09-18 23:19:31,560 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir IPAdapterStyleComposition' might differ from the native display name.
2024-09-18 23:19:31,562 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir UltimateSDUpscale' might differ from the native display name.
2024-09-18 23:19:31,566 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir MinusZoneChatGLM3TextEncode' might differ from the native display name.
2024-09-18 23:19:33,866 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir SamplerCustomAdvanced' might differ from the native display name.
2024-09-18 23:19:33,866 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir BasicGuider' might differ from the native display name.
2024-09-18 23:19:33,867 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir BasicScheduler' might differ from the native display name.
2024-09-18 23:19:33,867 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir DualCLIPLoader' might differ from the native display name.
2024-09-18 23:19:33,868 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir KSamplerSelect' might differ from the native display name.
2024-09-18 23:19:33,868 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir RandomNoise' might differ from the native display name.
2024-09-18 23:19:33,868 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir FluxGuidance' might differ from the native display name.
2024-09-18 23:19:42,800 - root - INFO - Total VRAM 12288 MB, total RAM 32677 MB
2024-09-18 23:19:42,800 - root - INFO - pytorch version: 2.4.0+cu124
2024-09-18 23:19:42,802 - root - INFO - xformers version: 0.0.27.post2
2024-09-18 23:19:42,802 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-18 23:19:42,802 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-09-18 23:19:45,160 - root - INFO - --------------
2024-09-18 23:19:45,160 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-09-18 23:19:45,161 - root - INFO - ChatGPT.available True
2024-09-18 23:19:45,162 - root - INFO - edit_mask.available True
2024-09-18 23:19:45,173 - root - INFO - LaMaInpainting.available True
2024-09-18 23:19:45,377 - root - INFO - ClipInterrogator.available True
2024-09-18 23:19:45,446 - root - INFO - PromptGenerate.available True
2024-09-18 23:19:45,447 - root - INFO - ChinesePrompt.available True
2024-09-18 23:19:45,447 - root - INFO - RembgNode_.available True
2024-09-18 23:19:46,436 - root - INFO - TripoSR.available
2024-09-18 23:19:46,437 - root - INFO - MiniCPMNode.available
2024-09-18 23:19:46,437 - root - INFO - [93m -------------- [0m
2024-09-18 23:20:03,661 - root - INFO - 
Import times for custom nodes:
2024-09-18 23:20:03,661 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
2024-09-18 23:20:03,662 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
2024-09-18 23:20:03,662 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-18 23:20:03,662 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-resize-comfyui
2024-09-18 23:20:03,665 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FatLabels
2024-09-18 23:20:03,665 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HyperSDXL1StepUnetScheduler
2024-09-18 23:20:03,665 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CascadeResolutions
2024-09-18 23:20:03,666 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MiniCPM-V
2024-09-18 23:20:03,666 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
2024-09-18 23:20:03,666 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt_injection
2024-09-18 23:20:03,666 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-09-18 23:20:03,666 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-StableDiffusion3-API
2024-09-18 23:20:03,667 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
2024-09-18 23:20:03,667 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
2024-09-18 23:20:03,667 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
2024-09-18 23:20:03,667 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-09-18 23:20:03,667 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
2024-09-18 23:20:03,668 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
2024-09-18 23:20:03,668 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-18 23:20:03,668 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-09-18 23:20:03,668 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-09-18 23:20:03,669 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Alimama-ControlNet-compatible
2024-09-18 23:20:03,669 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-18 23:20:03,669 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-09-18 23:20:03,669 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-09-18 23:20:03,669 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ELLA
2024-09-18 23:20:03,670 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-09-18 23:20:03,670 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
2024-09-18 23:20:03,670 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-SAL-VTON
2024-09-18 23:20:03,670 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-18 23:20:03,670 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-09-18 23:20:03,671 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
2024-09-18 23:20:03,671 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-09-18 23:20:03,671 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-09-18 23:20:03,671 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
2024-09-18 23:20:03,672 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
2024-09-18 23:20:03,672 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master
2024-09-18 23:20:03,672 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-18 23:20:03,672 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-09-18 23:20:03,672 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
2024-09-18 23:20:03,673 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
2024-09-18 23:20:03,673 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-18 23:20:03,673 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-18 23:20:03,673 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-09-18 23:20:03,674 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-09-18 23:20:03,675 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-18 23:20:03,675 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-18 23:20:03,675 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-18 23:20:03,675 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-18 23:20:03,676 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels
2024-09-18 23:20:03,676 - root - INFO -    0.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-09-18 23:20:03,676 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion
2024-09-18 23:20:03,676 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Remover
2024-09-18 23:20:03,677 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-18 23:20:03,677 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-18 23:20:03,678 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-18 23:20:03,678 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-09-18 23:20:03,678 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
2024-09-18 23:20:03,678 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
2024-09-18 23:20:03,678 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TrackingNodes
2024-09-18 23:20:03,679 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-liveportrait
2024-09-18 23:20:03,682 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-09-18 23:20:03,682 - root - INFO -    0.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-09-18 23:20:03,682 - root - INFO -    0.2 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
2024-09-18 23:20:03,683 - root - INFO -    0.2 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
2024-09-18 23:20:03,683 - root - INFO -    0.2 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-09-18 23:20:03,683 - root - INFO -    0.3 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-18 23:20:03,683 - root - INFO -    0.3 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini
2024-09-18 23:20:03,683 - root - INFO -    0.3 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AudioReactor
2024-09-18 23:20:03,684 - root - INFO -    0.5 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID-ZHO
2024-09-18 23:20:03,684 - root - INFO -    0.5 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstanceDiffusion
2024-09-18 23:20:03,684 - root - INFO -    0.7 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-09-18 23:20:03,684 - root - INFO -    1.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\a-person-mask-generator
2024-09-18 23:20:03,684 - root - INFO -    1.9 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
2024-09-18 23:20:03,685 - root - INFO -    2.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-09-18 23:20:03,685 - root - INFO -    2.0 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes
2024-09-18 23:20:03,685 - root - INFO -    3.2 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-09-18 23:20:03,685 - root - INFO -    4.1 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\BizyAir
2024-09-18 23:20:03,686 - root - INFO -    4.2 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-09-18 23:20:03,686 - root - INFO -    4.5 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-09-18 23:20:03,686 - root - INFO -    5.5 seconds: M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node
2024-09-18 23:20:03,686 - root - INFO - 
2024-09-18 23:20:03,710 - root - INFO - 

2024-09-18 23:20:03,711 - root - INFO - 

Starting server
2024-09-18 23:20:03,718 - root - INFO - [93mTo see the GUI go to: http://192.168.0.106:8188 or http://127.0.0.1:8188
2024-09-18 23:20:03,719 - root - INFO - [93mTo see the GUI go to: https://192.168.0.106:8189 or https://127.0.0.1:8189[0m
2024-09-18 23:21:22,862 - root - INFO - got prompt
2024-09-18 23:22:56,221 - root - ERROR - !!! Exception during processing !!! Pipeline <class 'ComfyUI_StoryDiffusion.utils.pipeline.PhotoMakerStableDiffusionXLPipeline'> expected {'unet', 'feature_extractor', 'vae', 'tokenizer_2', 'text_encoder_2', 'image_encoder', 'scheduler', 'text_encoder', 'tokenizer'}, but only {'vae', 'tokenizer_2', 'text_encoder_2', 'scheduler', 'text_encoder', 'tokenizer'} were passed.
2024-09-18 23:22:56,227 - root - ERROR - Traceback (most recent call last):
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1850, in story_model_loader
    pipe = load_models(repo_id, model_type=model_type, single_files=False, use_safetensors=True,photomake_mode=photomake_mode,
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 89, in load_models
    pipe = PhotoMakerStableDiffusionXLPipeline.from_pretrained(
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "M:\new222_ComfyUI\ComfyUI_windows_portable\.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 961, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'ComfyUI_StoryDiffusion.utils.pipeline.PhotoMakerStableDiffusionXLPipeline'> expected {'unet', 'feature_extractor', 'vae', 'tokenizer_2', 'text_encoder_2', 'image_encoder', 'scheduler', 'text_encoder', 'tokenizer'}, but only {'vae', 'tokenizer_2', 'text_encoder_2', 'scheduler', 'text_encoder', 'tokenizer'} were passed.

2024-09-18 23:22:56,229 - root - INFO - Prompt executed in 93.03 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":4,"last_link_id":3,"nodes":[{"id":2,"type":"Storydiffusion_Sampler","pos":{"0":467,"1":59,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":395.4347839355469,"1":750.820068359375},"flags":{},"order":2,"mode":0,"inputs":[{"name":"model","type":"STORY_DICT","link":1},{"name":"image","type":"IMAGE","link":2},{"name":"control_image","type":"IMAGE","link":null}],"outputs":[{"name":"image","type":"IMAGE","links":[3],"slot_index":0,"shape":3},{"name":"prompt_array","type":"STRING","links":null,"shape":3}],"properties":{"Node name for S&R":"Storydiffusion_Sampler"},"widgets_values":["[Taylor] a woman img, wearing a white T-shirt, blue loose hair.\n","[Taylor]wake up in the bed,medium shot;\n","","bad anatomy, bad hands, missing fingers, extra fingers, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, three crus, fused feet, fused thigh, extra crus, ugly fingers, horn,amputation, disconnected limbs","No_style",2068326615,"randomize",20,3.5,1,20,"none",0.8,0.5,5,false,"none",0.8,"0., 0.25, 0.4, 0.75;0.6, 0.25, 1., 0.75"]},{"id":4,"type":"SaveImage","pos":{"0":913,"1":61,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":3}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":3,"type":"LoadImage","pos":{"0":80,"1":549,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["2.png","image"]},{"id":1,"type":"Storydiffusion_Model_Loader","pos":{"0":62,"1":64,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":340.20001220703125,"1":418},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"STORY_DICT","links":[1],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"Storydiffusion_Model_Loader"},"widgets_values":["D:\\new222_ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\FLUX.1-dev","flux1-dev-fp8.safetensors","none","none","none",0.8,"best quality","Euler","img2img",1,0.5,0.5,768,768,"v1",""]}],"links":[[1,1,0,2,0,"STORY_DICT"],[2,3,0,2,1,"IMAGE"],[3,2,0,4,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.061076460950001,"offset":[420.79413936168515,229.08602168947294]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by smthemex** [comment]
Based on the error message, it is speculated that the error was caused by the use of flux. It should be due to the missing necessary files in the repo_id path you filled in. Please refer to the detailed list of diffuser file directories for flux in the readme. If you are using SDXL, there is no need to fill in any in the repo, just select the SDXL community model in ckpt_name. If the error persists, please replace the model as some models are not supported.
根据报错信息，推测是使用了flux的报错，应该是你填写的repo_id路径缺失了必要的文件，请查看readme 关于flux的diffuser文件目录的详细列表，如果你使用的是SDXL，无需在repo填写任何，只需要在ckpt_name选择sdxl社区模型，如果还报错，请更换一个模型，有些模型不支持。

**Comment by sunyiwk** [comment]
flux的diffuser文件描述是这些文件：
<html>
<body>

{
--
  | "_class_name": "FluxPipeline",
  | "_diffusers_version": "0.30.0.dev0",
  | "scheduler": [
  | "diffusers",
  | "FlowMatchEulerDiscreteScheduler"
  | ],
  | "text_encoder": [
  | "transformers",
  | "CLIPTextModel"
  | ],
  | "text_encoder_2": [
  | "transformers",
  | "T5EncoderModel"
  | ],
  | "tokenizer": [
  | "transformers",
  | "CLIPTokenizer"
  | ],
  | "tokenizer_2": [
  | "transformers",
  | "T5TokenizerFast"
  | ],
  | "transformer": [
  | "diffusers",
  | "FluxTransformer2DModel"
  | ],
  | "vae": [
  | "diffusers",
  | "AutoencoderKL"
  | ]
  | }


</body>
</html>
确实没有'unet', 'feature_extractor' 'image_encoder'这些啊

**Comment by smthemex** [comment]
还有个可能是，你填写的地址结尾不是"..../FLUX.1-dev",然后识别成了SDXL加载流程

**Comment by sunyiwk** [comment]
![QQ20240919-174006](https://github.com/user-attachments/assets/b391041a-9e09-4f3a-8f5e-e5ea82482f8a)
buguan不管用 他仍然检测SDXL加载流程
