### ISSUE TITLE
ModuleNotFoundError: No module named 'imwatermark'

### ISSUE THREAD

**Issue by kk84214** [smthemex/ComfyUI_StoryDiffusion#76]
requirements已经安装好，下面是完整报错信息：

Traceback (most recent call last):
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\pipeline.py", line 15, in <module>
    from diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl import StableDiffusionXLPipelineOutput, \
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\.ext\Lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py", line 40, in <module>
    from .watermark import StableDiffusionXLWatermarker
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\.ext\Lib\site-packages\diffusers\pipelines\stable_diffusion_xl\watermark.py", line 3, in <module>
    from imwatermark import WatermarkEncoder
ModuleNotFoundError: No module named 'imwatermark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\pipeline.py", line 19, in <module>
    from diffusers.pipelines.stable_diffusion_xl import StableDiffusionXLPipelineOutput,rescale_noise_cfg
ImportError: cannot import name 'rescale_noise_cfg' from 'diffusers.pipelines.stable_diffusion_xl' (D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\.ext\Lib\site-packages\diffusers\pipelines\stable_diffusion_xl\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\pipeline.py", line 22, in <module>
    from diffusers.pipelines.stable_diffusion_xl.pipeline_output import StableDiffusionXLPipelineOutput,rescale_noise_cfg
ModuleNotFoundError: No module named 'diffusers.pipelines.stable_diffusion_xl.pipeline_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 23, in <module>
    from .utils.gradio_utils import (
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\__init__.py", line 2, in <module>
    from .pipeline import PhotoMakerStableDiffusionXLPipeline
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\pipeline.py", line 24, in <module>
    raise "import StableDiffusionXLPipelineOutput,rescale_noise_cfg error"
TypeError: exceptions must derive from BaseException

Cannot import D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion module for custom nodes: exceptions must derive from BaseException

**Comment by kk84214** [comment]
Name: diffusers
Version: 0.30.3
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: diffusers@huggingface.co
License: Apache 2.0 License
Location: C:\Program Files\Python312\Lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors

大佬，是这个问题吗

**Comment by smthemex** [comment]
不对哦，难道是版本太高了，我看看新版的是不是改了什么

**Comment by smthemex** [comment]
你pip show的diffuser版本是C盘的啊，大佬，你的便携包里的diffuser版本呢，去 python_embeded\Lib\site-packages 下看看diffusers的版本

**Comment by kk84214** [comment]
便携包里没有diffuser，我已经晕了，怎么C盘还有一个环境。。。。我是用便携包和秋叶启动器。storydiffusion的requirements是在comfyui_nodes对应的目录下运行的。纯新手，一点python不懂，大佬费心

**Comment by smthemex** [comment]
秋叶可以调用C盘的，便携包也可以，不过要改一下配置，当然，既然便携了，当然要用独立的，避免冲突。

**Comment by kk84214** [comment]
感谢大佬，换了环境果然好了

**Comment by kk84214** [comment]
环境问题，现在已经ok了
