### ISSUE TITLE
使用Flux的情况下，一定要下载官方的所有模型吗？

### ISSUE THREAD

**Issue by prog-ape** [smthemex/ComfyUI_StoryDiffusion#77]
使用Flux的情况下，一定要下载官方的所有模型和配置文件吗？单独合并的或者单独gguf不支持？

**Comment by smthemex** [comment]
如果要走nf4或者fp8需要，pulid不需要，我只是懒得加节点接口而已

**Comment by prog-ape** [comment]
好的，谢谢

**Comment by prog-ape** [comment]
![image](https://github.com/user-attachments/assets/02c66796-3723-42ea-8d1b-a4d3d9fbed99)

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.05it/s]
Init model
Loading checkpoint in fp8
Start a quantization process...
Model is quantized!
Init AE
Loaded EVA02-CLIP-L-14-336 model config.
Shape of rope freq: torch.Size([576, 64])
Loading pretrained EVA02-CLIP-L-14-336 weights (D:\ai\ComfyUI\models\clip_vision\EVA02_CLIP_L_336_psz14_s6B.pt).
incompatible_keys.missing_keys: ['visual.rope.freqs_cos', 'visual.rope.freqs_sin', 'visual.blocks.0.attn.rope.freqs_cos', 'visual.blocks.0.attn.rope.freqs_sin', 'visual.blocks.1.attn.rope.freqs_cos', 'visual.blocks.1.attn.rope.freqs_sin', 'visual.blocks.2.attn.rope.freqs_cos', 'visual.blocks.2.attn.rope.freqs_sin', 'visual.blocks.3.attn.rope.freqs_cos', 'visual.blocks.3.attn.rope.freqs_sin', 'visual.blocks.4.attn.rope.freqs_cos', 'visual.blocks.4.attn.rope.freqs_sin', 'visual.blocks.5.attn.rope.freqs_cos', 'visual.blocks.5.attn.rope.freqs_sin', 'visual.blocks.6.attn.rope.freqs_cos', 'visual.blocks.6.attn.rope.freqs_sin', 'visual.blocks.7.attn.rope.freqs_cos', 'visual.blocks.7.attn.rope.freqs_sin', 'visual.blocks.8.attn.rope.freqs_cos', 'visual.blocks.8.attn.rope.freqs_sin', 'visual.blocks.9.attn.rope.freqs_cos', 'visual.blocks.9.attn.rope.freqs_sin', 'visual.blocks.10.attn.rope.freqs_cos', 'visual.blocks.10.attn.rope.freqs_sin', 'visual.blocks.11.attn.rope.freqs_cos', 'visual.blocks.11.attn.rope.freqs_sin', 'visual.blocks.12.attn.rope.freqs_cos', 'visual.blocks.12.attn.rope.freqs_sin', 'visual.blocks.13.attn.rope.freqs_cos', 'visual.blocks.13.attn.rope.freqs_sin', 'visual.blocks.14.attn.rope.freqs_cos', 'visual.blocks.14.attn.rope.freqs_sin', 'visual.blocks.15.attn.rope.freqs_cos', 'visual.blocks.15.attn.rope.freqs_sin', 'visual.blocks.16.attn.rope.freqs_cos', 'visual.blocks.16.attn.rope.freqs_sin', 'visual.blocks.17.attn.rope.freqs_cos', 'visual.blocks.17.attn.rope.freqs_sin', 'visual.blocks.18.attn.rope.freqs_cos', 'visual.blocks.18.attn.rope.freqs_sin', 'visual.blocks.19.attn.rope.freqs_cos', 'visual.blocks.19.attn.rope.freqs_sin', 'visual.blocks.20.attn.rope.freqs_cos', 'visual.blocks.20.attn.rope.freqs_sin', 'visual.blocks.21.attn.rope.freqs_cos', 'visual.blocks.21.attn.rope.freqs_sin', 'visual.blocks.22.attn.rope.freqs_cos', 'visual.blocks.22.attn.rope.freqs_sin', 'visual.blocks.23.attn.rope.freqs_cos', 'visual.blocks.23.attn.rope.freqs_sin']
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ai\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ai\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ai\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ai\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1893, in story_model_loader
    pipe = FluxGenerator(repo_id, ckpt_path, "cuda", offload=True,
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\PuLID\app_flux.py", line 37, in __init__
    self.pulid_model = PuLIDPipeline(self.model, device, self.clip_vision_path,weight_dtype=torch.bfloat16)
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\PuLID\pulid\pipeline_flux.py", line 161, in __init__
    self.app = FaceAnalysis(
  File "D:\anaconda3\envs\comfyui\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

请问这种异常如何解决？

**Comment by smthemex** [comment]
insightface模型不对，或者没找到

**Comment by prog-ape** [comment]
insightface需要哪个版本

**Comment by prog-ape** [comment]
![image](https://github.com/user-attachments/assets/d71f86ab-567b-4dfc-bff4-78b80a1b1a11)
就差一个没安装

**Comment by smthemex** [comment]
ox装了没有？

**Comment by prog-ape** [comment]
pip show onnxruntime-gpu
Name: onnxruntime-gpu
Version: 1.15.1

**Comment by smthemex** [comment]
奇怪了，我刚才查了下insightface的报错位置，的确是模型的问题，在comfyUI/models/antelopev2目录下或者cache目录下确认是否有glintr100.onnx，以及
![image](https://github.com/user-attachments/assets/2ddc3cdf-1fe6-423e-ba13-c369347a0516)

**Comment by prog-ape** [comment]
谢谢，确定了问题那就好解决
