### ISSUE TITLE
about:"not used when initializing CLIPTextModel:"

### ISSUE THREAD

**Issue by tiandaoyuxi** [smthemex/ComfyUI_StoryDiffusion#78]
got prompt
run in id number 1
Loading pipeline components...:   0%|                                                  | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel:
 ['text_projection.weight']
Loading pipeline components...:  29%|████████████                              | 2/7 [00:00<00:00, 23.99it/s]
Loading pipeline components...:   0%|                                                  | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel:
 ['text_projection.weight']
Loading pipeline components...:  29%|████████████                              | 2/7 [00:00<00:00, 26.04it/s]
!!! Exception during processing !!! exceptions must derive from BaseException
Traceback (most recent call last):
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 103, in load_models
    pipe = PhotoMakerStableDiffusionXLPipelineV2.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 495, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 113, in load_single_file_sub_model
    loaded_sub_model = create_diffusers_clip_model_from_ldm(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 1457, in create_diffusers_clip_model_from_ldm
    raise ValueError("The provided checkpoint does not seem to contain a valid CLIP model.")
ValueError: The provided checkpoint does not seem to contain a valid CLIP model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 108, in load_models
    pipe = PhotoMakerStableDiffusionXLPipelineV2.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 495, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 113, in load_single_file_sub_model
    loaded_sub_model = create_diffusers_clip_model_from_ldm(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\python_embeded\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 1457, in create_diffusers_clip_model_from_ldm
    raise ValueError("The provided checkpoint does not seem to contain a valid CLIP model.")
ValueError: The provided checkpoint does not seem to contain a valid CLIP model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Comfy_UI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Comfy_UI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1721, in story_model_loader
    pipe = load_models(ckpt_path, model_type=model_type, single_files=True, use_safetensors=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\load_models_utils.py", line 113, in load_models
    raise "load pipe error"
TypeError: exceptions must derive from BaseException

**Comment by smthemex** [comment]
change another checkpoint
