### ISSUE TITLE
加载报错 No module named 'ComfyUI'

### ISSUE THREAD

**Issue by kk84214** [smthemex/ComfyUI_StoryDiffusion#85]
Traceback (most recent call last):
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\__init__.py", line 2, in <module>
    from .Storydiffusion_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 19, in <module>
    import ComfyUI.comfy.model_sampling
ModuleNotFoundError: No module named 'ComfyUI'

Cannot import D:\Program Files\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion module for custom nodes: No module named 'ComfyUI'

**Comment by smthemex** [comment]
更新下，或者你把这行代码删掉
Update it, or you can delete this line of code

**Comment by kk84214** [comment]
更新并删掉对应的代码
