### ISSUE TITLE
Storydiffusion_Model_Loader

### ISSUE THREAD

**Issue by AoeSyL** [smthemex/ComfyUI_StoryDiffusion#86]
got prompt
2024-09-28 22:00:06.415988 run in id number ： 1
2024-09-28 22:00:06.416957 Init model in fp8

2024-09-28 22:01:44.732608 Start a quantization process...
2024-09-28 22:02:54.907596 Model is quantized!
2024-09-28 22:02:55.154598 Init AE
Loaded EVA02-CLIP-L-14-336 model config.
Shape of rope freq: torch.Size([576, 64])
Loading pretrained EVA02-CLIP-L-14-336 weights (/home/ubuntu/ComfyUI/models/clip_vision/EVA02_CLIP_L_336_psz14_s6B.pt).
incompatible_keys.missing_keys: ['visual.rope.freqs_cos', 'visual.rope.freqs_sin', 'visual.blocks.0.attn.rope.freqs_cos', 'visual.blocks.0.attn.rope.freqs_sin', 'visual.blocks.1.attn.rope.freqs_cos', 'visual.blocks.1.attn.rope.freqs_sin', 'visual.blocks.2.attn.rope.freqs_cos', 'visual.blocks.2.attn.rope.freqs_sin', 'visual.blocks.3.attn.rope.freqs_cos', 'visual.blocks.3.attn.rope.freqs_sin', 'visual.blocks.4.attn.rope.freqs_cos', 'visual.blocks.4.attn.rope.freqs_sin', 'visual.blocks.5.attn.rope.freqs_cos', 'visual.blocks.5.attn.rope.freqs_sin', 'visual.blocks.6.attn.rope.freqs_cos', 'visual.blocks.6.attn.rope.freqs_sin', 'visual.blocks.7.attn.rope.freqs_cos', 'visual.blocks.7.attn.rope.freqs_sin', 'visual.blocks.8.attn.rope.freqs_cos', 'visual.blocks.8.attn.rope.freqs_sin', 'visual.blocks.9.attn.rope.freqs_cos', 'visual.blocks.9.attn.rope.freqs_sin', 'visual.blocks.10.attn.rope.freqs_cos', 'visual.blocks.10.attn.rope.freqs_sin', 'visual.blocks.11.attn.rope.freqs_cos', 'visual.blocks.11.attn.rope.freqs_sin', 'visual.blocks.12.attn.rope.freqs_cos', 'visual.blocks.12.attn.rope.freqs_sin', 'visual.blocks.13.attn.rope.freqs_cos', 'visual.blocks.13.attn.rope.freqs_sin', 'visual.blocks.14.attn.rope.freqs_cos', 'visual.blocks.14.attn.rope.freqs_sin', 'visual.blocks.15.attn.rope.freqs_cos', 'visual.blocks.15.attn.rope.freqs_sin', 'visual.blocks.16.attn.rope.freqs_cos', 'visual.blocks.16.attn.rope.freqs_sin', 'visual.blocks.17.attn.rope.freqs_cos', 'visual.blocks.17.attn.rope.freqs_sin', 'visual.blocks.18.attn.rope.freqs_cos', 'visual.blocks.18.attn.rope.freqs_sin', 'visual.blocks.19.attn.rope.freqs_cos', 'visual.blocks.19.attn.rope.freqs_sin', 'visual.blocks.20.attn.rope.freqs_cos', 'visual.blocks.20.attn.rope.freqs_sin', 'visual.blocks.21.attn.rope.freqs_cos', 'visual.blocks.21.attn.rope.freqs_sin', 'visual.blocks.22.attn.rope.freqs_cos', 'visual.blocks.22.attn.rope.freqs_sin', 'visual.blocks.23.attn.rope.freqs_cos', 'visual.blocks.23.attn.rope.freqs_sin']
!!! Exception during processing !!! 
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ubuntu/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/Storydiffusion_node.py", line 1965, in story_model_loader
    pipe = FluxGenerator(flux_pulid_name, ckpt_path, "cuda", offload=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/PuLID/app_flux.py", line 39, in __init__
    self.pulid_model = PuLIDPipeline(self.model, device, self.clip_vision_path,weight_dtype=torch.bfloat16)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/PuLID/pulid/pipeline_flux.py", line 161, in __init__
    self.app = FaceAnalysis(
               ^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/comfyui/lib/python3.12/site-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 181.27 seconds

**Comment by smthemex** [comment]
This location error is usually caused by insightface not being installed properly or unable to automatically download model files
这个位置报错一般是insightface没有安装好，或者无法自动下载模型文件

**Comment by AoeSyL** [comment]
```models

.
├── antelopev2
│   ├── 1k3d68.onnx
│   ├── 2d106det.onnx
│   ├── genderage.onnx
│   ├── glintr100.onnx
│   └── scrfd_10g_bnkps.onnx
├── antelopev2.zip
├── checkpoints
│   ├── FLUX1
│   │   └── flux1-dev-fp8.safetensors
│   ├── flux1-dev-fp8.safetensors
│   └── put_checkpoints_here
├── clip
│   ├── clip_l.safetensors
│   ├── put_clip_or_text_encoder_models_here
│   └── t5xxl_fp8_e4m3fn.safetensors
├── clip_vision
│   ├── EVA02_CLIP_L_336_psz14_s6B.pt
│   └── put_clip_vision_models_here
├── configs
│   ├── anything_v3.yaml
│   ├── v1-inference_clip_skip_2_fp16.yaml
│   ├── v1-inference_clip_skip_2.yaml
│   ├── v1-inference_fp16.yaml
│   ├── v1-inference.yaml
│   ├── v1-inpainting-inference.yaml
│   ├── v2-inference_fp32.yaml
│   ├── v2-inference-v_fp32.yaml
│   ├── v2-inference-v.yaml
│   ├── v2-inference.yaml
│   └── v2-inpainting-inference.yaml
├── controlnet
│   └── put_controlnets_and_t2i_here
├── diffusers
│   └── put_diffusers_models_here
├── diffusion_models
│   └── put_diffusion_model_files_here
├── dz_facedetailer
│   └── yolo
│       └── face_yolov8n.pt
├── embeddings
│   └── put_embeddings_or_textual_inversion_concepts_here
├── facedetection
│   ├── detection_Resnet50_Final.pth
│   ├── parsing_parsenet.pth
│   └── yolov5l-face.pth
├── facerestore_models
│   ├── codeformer-v0.1.0.pth
│   ├── GFPGANv1.3.pth
│   ├── GFPGANv1.4.pth
│   ├── GPEN-BFR-1024.onnx
│   ├── GPEN-BFR-2048.onnx
│   └── GPEN-BFR-512.onnx
├── FLUX.1-dev
│   ├── ae.safetensors
│   ├── dev_grid.jpg
│   ├── flux1-dev.safetensors
│   ├── LICENSE.md
│   ├── model_index.json
│   ├── README.md
│   ├── scheduler
│   │   └── scheduler_config.json
│   ├── text_encoder
│   │   ├── config.json
│   │   └── model.safetensors
│   ├── text_encoder_2
│   │   ├── config.json
│   │   ├── model-00001-of-00002.safetensors
│   │   ├── model-00002-of-00002.safetensors
│   │   └── model.safetensors.index.json
│   ├── tokenizer
│   │   ├── merges.txt
│   │   ├── special_tokens_map.json
│   │   ├── tokenizer_config.json
│   │   └── vocab.json
│   ├── tokenizer_2
│   │   ├── special_tokens_map.json
│   │   ├── spiece.model
│   │   ├── tokenizer_config.json
│   │   └── tokenizer.json
│   ├── transformer
│   │   ├── config.json
│   │   ├── diffusion_pytorch_model-00001-of-00003.safetensors
│   │   ├── diffusion_pytorch_model-00002-of-00003.safetensors
│   │   ├── diffusion_pytorch_model-00003-of-00003.safetensors
│   │   └── diffusion_pytorch_model.safetensors.index.json
│   └── vae
│       ├── config.json
│       └── diffusion_pytorch_model.safetensors
├── gligen
│   └── put_gligen_models_here
├── hypernetworks
│   └── put_hypernetworks_here
├── insightface
│   ├── inswapper_128.onnx
│   └── models
│       ├── antelopev2
│       │   ├── 1k3d68.onnx
│       │   ├── 2d106det.onnx
│       │   ├── genderage.onnx
│       │   ├── glintr100.onnx
│       │   └── scrfd_10g_bnkps.onnx
│       └── buffalo_l
│           ├── 1k3d68.onnx
│           ├── 2d106det.onnx
│           ├── det_10g.onnx
│           ├── genderage.onnx
│           └── w600k_r50.onnx
├── lama
├── loras
│   ├── flux_realism_lora.safetensors
│   └── put_loras_here
├── photomaker
│   ├── ip_adapter_plus_general.bin
│   ├── mask.bin
│   ├── photomaker-v1.bin
│   ├── photomaker-v2.bin
│   ├── pt
│   ├── pulid_flux_v0.9.0.safetensors
│   └── put_photomaker_models_here
├── pulid
│   ├── b258a5cd2c0c7d35f4d3e59909d7648498686afae4d0c74917e9c47d7704fbf5?response-content-disposition=attachment;+filename*=UTF-8''ip-adapter_pulid_sdxl_fp16.safetensors;+filename="ip-adapter_pulid_sdxl_fp16.safetensors";&Expires=1727751576&Pol
│   ├── wget-log
│   └── wget-log.1
├── reactor
│   └── faces
├── style_models
│   └── put_t2i_style_model_here
├── unet
│   ├── flux1-dev-fp8.safetensors
│   └── put_unet_files_here
├── upscale_models
│   ├── 4x-UltraSharp.pth
│   └── put_esrgan_and_other_upscale_models_here
├── vae
│   ├── ae.safetensors
│   ├── FLUX1
│   │   └── ae.sft
│   └── put_vae_here
└── vae_approx
    ├── put_taesd_encoder_pth_and_taesd_decoder_pth_here
    └── taef1_decoder.pth
```

```pip list 
Package                   Version
------------------------- ------------------
absl-py                   2.1.0
accelerate                0.31.0
addict                    2.4.0
aiofiles                  23.2.1
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
albucore                  0.0.13
albumentations            1.4.14
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.4.0
anykeystore               0.2
apex                      0.9.10.dev0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
attrs                     24.2.0
beautifulsoup4            4.12.3
binaryornot               0.4.4
boto3                     1.34.86
botocore                  1.34.162
Brotli                    1.0.9
certifi                   2024.7.4
cffi                      1.17.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
clip-interrogator         0.6.0
coloredlogs               15.0.1
colorlog                  6.8.2
colour-science            0.4.4
contourpy                 1.2.1
cookiecutter              2.6.0
cryptacular               1.6.2
cryptography              43.0.0
cssselect2                0.7.0
cycler                    0.12.1
Cython                    3.0.11
defusedxml                0.7.1
Deprecated                1.2.14
diffusers                 0.30.0
easydict                  1.13
einops                    0.8.0
embreex                   2.17.7.post5
eval_type_backport        0.2.0
facexlib                  0.3.0
fal_client                0.4.1
fastapi                   0.114.0
ffmpy                     0.4.0
filelock                  3.13.1
filterpy                  1.4.5
fire                      0.5.0
flatbuffers               24.3.25
flet                      0.24.1
flet-core                 0.24.1
flet-runtime              0.24.1
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
ftfy                      6.2.3
future                    1.0.0
fvcore                    0.1.5.post20221221
gdown                     5.2.0
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    4.44.0
gradio_client             1.3.0
gray2color                0.4.3
greenlet                  3.1.1
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.2
httpx-sse                 0.4.0
huggingface-hub           0.24.6
humanfriendly             10.0
hupper                    1.12.1
idna                      3.7
imageio                   2.35.1
importlib_metadata        8.4.0
importlib_resources       6.4.5
insightface               0.7.3
iopath                    0.1.10
jax                       0.4.31
jaxlib                    0.4.31
Jinja2                    3.1.4
jmespath                  1.0.1
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.7.3
kornia_rs                 0.1.5
lark-parser               0.12.0
lazy_loader               0.4
llvmlite                  0.43.0
lmdb                      1.5.1
lpips                     0.1.4
lxml                      5.3.0
manifold3d                2.5.1
mapbox_earcut             1.0.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.9.2
matrix-client             0.4.0
mdurl                     0.1.2
mediapipe                 0.10.15
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
ml-dtypes                 0.4.0
mpmath                    1.3.0
multidict                 6.0.5
networkx                  3.3
ninja                     1.11.1.1
numba                     0.60.0
numpy                     1.26.4
oauthlib                  3.2.2
omegaconf                 2.3.0
onnx                      1.16.2
onnxruntime               1.19.0
onnxruntime-gpu           1.19.0
open_clip_torch           2.26.1
opencv-contrib-python     4.10.0.84
opencv-python             4.8.1.78
opencv-python-headless    4.10.0.84
opt-einsum                3.3.0
optimum-quanto            0.2.4
orjson                    3.10.7
packaging                 23.2
pandas                    2.2.2
PasteDeploy               3.1.0
pbkdf2                    1.3
peft                      0.12.0
piexif                    1.1.3
pillow                    10.4.0
pip                       24.2
pixeloe                   0.0.10
plaster                   1.1.2
plaster-pastedeploy       1.0.1
platformdirs              4.3.2
pooch                     1.8.2
portalocker               2.10.1
prettytable               3.11.0
protobuf                  4.25.4
psutil                    5.9.8
py-cpuinfo                9.0.0
pycollada                 0.8
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
PyGithub                  2.3.0
Pygments                  2.18.0
PyJWT                     2.9.0
PyMatting                 1.1.12
PyNaCl                    1.5.0
pyparsing                 3.1.2
pypng                     0.20220715.0
pyramid                   2.0.2
pyramid-mailer            0.15.1
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.10
python-slugify            8.0.4
python3-openid            3.2.0
pytz                      2024.1
PyWavelets                1.7.0
PyYAML                    6.0.1
qrcode                    7.4.2
redis                     5.0.8
referencing               0.35.1
regex                     2024.7.24
rembg                     2.0.59
repath                    0.9.0
reportlab                 4.2.2
repoze.sendmail           4.4.1
requests                  2.32.3
requests-oauthlib         2.0.0
rich                      13.7.1
rpds-py                   0.20.0
Rtree                     1.3.0
ruff                      0.6.8
s3transfer                0.10.2
safetensors               0.4.5
scikit-image              0.24.0
scikit-learn              1.5.1
scipy                     1.14.1
seaborn                   0.13.2
segment-anything          1.0
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                72.1.0
shapely                   2.0.6
shellingham               1.5.4
simple-lama-inpainting    0.1.2
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sounddevice               0.5.0
soundfile                 0.12.1
soupsieve                 2.6
spaces                    0.30.2
spandrel                  0.3.4
SQLAlchemy                2.0.35
starlette                 0.38.5
surrealist                0.5.3
svg.path                  6.3
svglib                    1.5.1
sympy                     1.12
tabulate                  0.9.0
termcolor                 2.4.0
text-unidecode            1.3
threadpoolctl             3.5.0
tifffile                  2024.8.10
timm                      1.0.8
tinycss2                  1.3.0
tokenizers                0.19.1
tomli                     2.0.1
tomlkit                   0.12.0
torch                     2.4.1
torchaudio                2.4.1
torchsde                  0.2.6
torchvision               0.19.1
tqdm                      4.66.5
trampoline                0.1.2
transaction               5.0
transformers              4.44.1
translationstring         1.4
transparent-background    1.3.2
trimesh                   4.4.9
triton                    3.0.0
typer                     0.12.4
types-python-dateutil     2.9.0.20240906
typing_extensions         4.11.0
tzdata                    2024.1
ultralytics               8.2.79
ultralytics-thop          2.0.5
urllib3                   2.2.3
uvicorn                   0.30.6
uvloop                    0.20.0
velruse                   1.1.1
venusian                  3.1.0
vhacdx                    0.0.8.post1
watchdog                  4.0.2
watchfiles                0.24.0
wcwidth                   0.2.13
webencodings              0.5.1
WebOb                     1.8.8
websocket-client          1.8.0
websockets                12.0
wget                      3.2
wheel                     0.43.0
wrapt                     1.16.0
WTForms                   3.1.2
wtforms-recaptcha         0.3.2
xatlas                    0.0.9
xformers                  0.0.28.post1
xxhash                    3.5.0
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.20.0
zope.deprecation          5.0
zope.interface            7.0.3
zope.sqlalchemy           3.1

```

**Comment by AoeSyL** [comment]
when i reinstall insightface, but the error still persisted.
how should I handle it?
missing models or something else?

**Comment by smthemex** [comment]
try uninstall onnxruntime-gpu
